server:
  port: 80

spring:
  application:
    name: order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机版

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。